name: Build and deploy client

on:
  push:
    branches: ["main"]
    paths:
      - "client/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: install yarn and dependencies
        run: |
          npm i -g yarn
          cd client
          yarn install
          yarn build
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: client/dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: mkdir ~/distfiles
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: ~/distfiles
      - name: list files
        run: |
          which scp 
          cd ~
          echo ${{secrets.SSHKEY}} >> ./id_rsa
          ls -a
          scp -o "StrictHostKeyChecking=no" -i ./id_rsa ./distfiles ${{ secrets.USERNAME }}@${{ secrets.SERVERIP }}:~/watchwithfriends/website
