name: Build Server

on:
  push:
    branches: ["main"]
    paths:
      - "server/**"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Build
      - run: cd server && cargo build --verbose --release
      - uses: actions/upload-artifact@v3
        with:
          name: server-build
          path: server/target/release/watchwithfriends-4

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: server-build

      - shell: bash
        env:
          SSH_KEY: ${{ secrets.SSHKEY }}
          SERVER_IP: ${{ secrets.SERVERIP }}
        run: |
          mkdir .ssh
          touch .ssh/id_rsa.pub
          echo "$SSH_KEY" > .ssh/id_rsa.pub
          scp ./server-build watchwithfriends@"$SERVER_IP":~/watchwithfriends/server
